# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')])),
                ('school_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')])),
                ('year_in_school', models.IntegerField(choices=[(0, 'Elige tu año escolar'), (1, '1ro'), (2, '2do'), (3, '3ro'), (4, '4to'), (5, '5to')], default=0)),
                ('cities', models.IntegerField(choices=[(0, 'Elige una ciudad Sede'), (1, 'Arequipa'), (2, 'Cusco')], default=0)),
            ],
        ),
    ]
