# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 00:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_register_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(error_messages={'invalid': 'El campo ingresado es inválido', 'required': 'Este campo es requerido'}, max_length=200, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')]),
        ),
    ]
