# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170713_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(error_messages={'required': 'Este campo es requerido'}, max_length=200),
        ),
    ]
