# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170713_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='year_in_school',
            field=models.IntegerField(choices=[(0, 'Elige tu año escolar'), (1, '1ro'), (2, '2do'), (3, '3ro'), (4, '4to'), (5, '5to')], default=0),
        ),
    ]
